services:
  postgres:
    image: postgres:16-alpine
    container_name: meetpilot-app
    restart: unless-stopped
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meetpilot_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
